### ISSUE TITLE
Transparent window renders black background after display settings changed

### ISSUE THREAD

**Issue by CharlieHess** [atom/electron#1270]
Over in Slack land, this is becoming one of our highest-priority bugs. We create a transparent window to host notifications and _most_ of the time, it works well. Occasionally after users modify their display settings (say, by connecting to external monitors), the window loses its transparency and instead renders a black background:
![](https://s3.amazonaws.com/f.cl.ly/items/011D312s2P132x2e330n/Image%202015-03-20%20at%2010.44.04%20AM.png)

@zcbenz: Any ideas here?

**Comment by zcbenz** [comment]
It seems that we need to reset window style when display setting changes, it could also be a bug of Chromium, I will take a look.

**Comment by paulcbetts** [comment]
The only 100% repro I've heard of for this bug was a guy who said:

1. Have a Geforce 970-series (or recent Geforce with newest drivers)
1. Remote desktop into the machine, then disconnect
1. Get a notification again, the app is jacked.

If you select some text in the current app then right click, "Inspect Element" will get you Devtools if you want to poke around in our app

**Comment by zcbenz** [comment]
Hmm I didn't succeed to reproduce it, and it seems that window styles are fine between display setting changes. It might be some bug in Chromium's GPU composition.

I think you can recreate the window when display settings changes to work around it.

**Comment by pcamp72** [comment]
I found the same problem, the only way around it was to set slightly increase and decrease your width/height.. 

me.width -=1
me.height -=1
me.width +=1
me.height +=1

**Comment by zcbenz** [comment]
It seems to have been fixed by Chrome47 upgrade in 0.36.x.

**Comment by sebbyt16** [comment]
Any chance this has been reopened, as it is still an issue?

Windows 10 Home, remote desktop connection to a Windows 8.1 Pro machine. Seems like every time I do this, I get a large black box in the bottom right corner of the RDC screen. I also noticed the other day that every once in a while (haven't figured out exactly when/why/how) I get a transparent window in the same spot when I am physically logged into the Windows 8.1 machine. Which is a real pain as it is invisible, on top of all other windows, and tough to debug.

Using Chrome Version 48.0.2564.116 m.

**Comment by pcamp72** [comment]
I found the same problem, the only way around it was to set slightly increase and decrease your width/height.. 

me.width -=1
 me.height -=1
 me.width +=1
 me.height +=1

**Comment by davidlonguk** [comment]
I get this problem with the slack desktop client, I don't even need chrome to be open to see the issue.
Also using a laptop using both Intel and Nvidia 970m graphics cards with latest drivers.

**Comment by MattJeanes** [comment]
After the latest slack update which goes back to this rather than native Windows notifications this has become an issue again- particularly over remote desktop

**Comment by BellaJTam** [comment]
This is also happening to me when I have slack notifications appear on the same monitor as my Slack application.
Current setup: Extended Desktop from a Laptop connected to 2 monitors. Slack app (and notifications are on Monitor 2)

**Comment by davidlonguk** [comment]
The only solution I have found so far is to go into my slack desktop app preferences and change the "Deliver notifications via..." from Slack builtin notifications to Windows Action Center. They are not as nice as the slack notifications and you can't click reply directly on them but they do not block half my screen with a black box every time I get a notification.

**Comment by mitcht** [comment]
I can concur. Using the slack application, I see the following black box when using built-in slack notifications. http://tinyurl.com/y4ncy4dg.

**Comment by archon810** [comment]
All my Slack notifications have a black background on Windows 10. As per Slack support, after disabling hardware acceleration in the settings, the issue is resolved. Took like a year to figure this out.

**Comment by eladmeidar** [comment]
Hi all, have the same experience but only on Windows 10 pro (1903) with a frameless, transparent window with `-webkit-app-region: drag;` - sometimes when dragging the window out of screen (even paretially) the part that went out of the view port, turns black when coming back (screenshot attached: https://i.stack.imgur.com/J3wzF.jpg
any followup on this issue?

**Comment by dillydadally** [comment]
Why is this closed? This is not fixed. I still have this issue daily. Notifications in Slack leave a big black rectangle behind.

**Comment by CSpy163** [comment]
> Hi all, have the same experience but only on Windows 10 pro (1903) with a frameless, transparent window with `-webkit-app-region: drag;` - sometimes when dragging the window out of screen (even paretially) the part that went out of the view port, turns black when coming back (screenshot attached: https://i.stack.imgur.com/J3wzF.jpg
> any followup on this issue?

Hi, did you resolve it?

**Comment by shion-pro** [comment]
> > Hi all, have the same experience but only on Windows 10 pro (1903) with a frameless, transparent window with `-webkit-app-region: drag;` - sometimes when dragging the window out of screen (even paretially) the part that went out of the view port, turns black when coming back (screenshot attached: https://i.stack.imgur.com/J3wzF.jpg
> > any followup on this issue?
> 
> Hi, did you resolve it?

I have the same issue

**Comment by fengyy51** [comment]
Hi, did you resolve it? I have the msame issue @eladmeidar

**Comment by lxfater** [comment]
> Hi, did you resolve it? I have the msame issue @eladmeidar

Did you resolve this it?
