### ISSUE TITLE
Electron Helper process marked as "(Not Responding)"

### ISSUE THREAD

**Issue by tommoor** [atom/electron#1844]
The Electron Helper processes in OSX are marked as Not Responding, this doesn't appear to affect the running of the app however we've had several users complain as they assume (rightly so) that it has crashed in some way.

Electron is the only app I have that seems to behave like this, I know that chromium used to but this doesn't seem to be the case in recent releases...

![image](https://cloud.githubusercontent.com/assets/380914/7925769/c70737ba-087d-11e5-8754-b869820cc3a6.png)

**Comment by ApfelUser** [comment]
There are other apps too, e.g. Brackets:

adobe/brackets#5794

**Comment by zcbenz** [comment]
I haven't seen it in recent releases, which version of Electron are you using?

**Comment by tommoor** [comment]
This is using the latest build. 0.27.2

**Comment by zcbenz** [comment]
Related Chromium issue: https://code.google.com/p/chromium/issues/detail?id=397642.

**Comment by tommoor** [comment]
@zcbenz do you see this on Atom? I'm interested that the chromium issue was closed last year, is there something that needs to be merged into Electron? Intrigued as to what needs to happen here... thanks!

**Comment by zcbenz** [comment]
@tommoor It happens for Atom, Electron should already have the fix in Chromium, I don't understand why it still happens sometimes.

**Comment by tommoor** [comment]
@zcbenz thanks. In our app it's not sometimes, it seems to be pretty much all of the time if you leave it open for a little while. Perhaps a clue? It's frustrating because users think the app is buggy and crashed

**Comment by tommoor** [comment]
Nudging this issue because I think it's a lot more important than it's being given credit for. 

When atom/electron is marked as not responding in bright red the user understandably thinks that the app has crashed, this gives a really negative impression.

**Comment by paulcbetts** [comment]
fwiw, this bug is fixed on Electron v0.30.0 on OS X 10.11

**Comment by kevinsawicki** [comment]
@tommoor are you still seeing this on Electron 0.30+ or can this be closed?

**Comment by tommoor** [comment]
@kevinsawicki still seeing the issue. I don't believe anything has been done to tackle it?

**Comment by kevinsawicki** [comment]
>  still seeing the issue on 0.30.4. I don't believe anything has been done to tackle it?

Okay, good to know, was just wondering given @paulcbetts's comment:

> fwiw, this bug is fixed on Electron v0.30.0 on OS X 10.11

**Comment by zcbenz** [comment]
Haven't seen this for a long time in recent versions.

**Comment by wialy** [comment]
Still have this bug using Electron v0.36.3 on OS X Yosemite 10.10.2. The applications works fine, just marked as `Not responding` in the Activity Monitor
