### ISSUE TITLE
Crash Reporter process is hanging after closing app

### ISSUE THREAD

**Issue by frankhale** [atom/electron#2209]
I don't know if this is my apps problem or Electron's problem. I'm seeing hanging Electron processes after quitting my app (just one Electron process to be specific). I think it's linked to webview usage but I cannot be sure. It doesn't happen all the time but it happens more often than not. 

Question, has anyone encountered this and if so is there any specific things I should avoid doing so that when I quit my app Electron doesn't hang? I don't think I'm doing anything crazy, I'm using webviews in a pretty straight forward way that I don't think should cause any issues.

I realize I am not providing any code samples here. I can if need be, really what I'm after is if anyone knows of any gotcha's, best practices and such for avoiding such scenarios.

**Comment by jprichardson** [comment]
Are you running Mac OS X?

**Comment by frankhale** [comment]
Sorry, running on Windows 8.1 and 10

**Comment by zcbenz** [comment]
Can you paste the command line parameters of the hanging processes? And are you using v0.29.x? There is a crash on quit problem fixed by #2211.

**Comment by frankhale** [comment]
I've seen this for a quite a long time on various versions. I am on 0.29.2 now but I will compile from master and see if #2211 fixes it for me. Thank you!

**Comment by frankhale** [comment]
I'm still seeing one process hang after quiting my app using 0.29.2 master (just cloned today). I'll try to create a small example to demonstrate the issue. I think it's related to using webviews. Processes don't seem to hang running the default app (at least in my tests).

**Comment by frankhale** [comment]
The behavior is intermittent but leaning towards 85% hanging process. Sometimes I get lucky and it quits cleanly.

**Comment by zcbenz** [comment]
Can you paste the command line parameters of the hanging processes? It can be got with tools like [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx).

**Comment by frankhale** [comment]
Yes I will get this info.

**Comment by frankhale** [comment]
There are no useful command line parameters. All I see on the hanging electron.exe process is this:

```
--reporter-url=http://xxx.xxx.xxx.xxx:xxxx/post --application-name=my_app_name --v=1
```

crash report IP omitted.

**Comment by zcbenz** [comment]
Hmm it is the crash handler process, not sure why it doesn't exit.

**Comment by frankhale** [comment]
I'm going to close this until I can provide a simple example which won't happen before next week.

**Comment by OlsonDev** [comment]
I just ran across this issue myself, with similar command line parameters. The thing I noticed is it only happens if I have Atom running. More specifically:

- Build & run my app with Atom: electron does not shut down entirely.
- Build & run my app with Sublime Text, Atom running: electron does not shut down entirely.
- Build & run my app with Sublime Text, then open Atom, then exit: electron shuts down cleanly.
- Build & run my app with Sublime Text, Atom not running nor opened: electron shuts down cleanly.

@frankhale, do you have time to confirm this scenario?

**Comment by frankhale** [comment]
This is interesting because I normally always have Atom opened. Let me try running my app without Atom opened and see if I can get a clean shutdown.

**Comment by frankhale** [comment]
@OlsonDev, yes I can confirm that this behavior. If I have Atom open and run my app and close my app one electron process will hang. If I open my app without Atom open and then close my app it closes cleanly. I repeated this process several times and it holds water.

I'm going to see if this is because I've started the crash reporter in my code. I'll remove crash reporter and see if it closes cleanly when Atom is open. Maybe there is some weirdness with crash reporter? I did see those command line switches on the hung electron process and only on that process.

**Comment by frankhale** [comment]
Looks like Crash Reporter is the culprit. I commented out the code that starts Crash Reporter in my main script and my app closes cleanly when Atom is opened.

**Comment by OlsonDev** [comment]
I didn't even know I was running the `crash-reporter`; evidently `require('crash-reporter').start();` is in the Quick Start guide I copy-pasted. I commented that out and can confirm it shuts down cleanly with Atom running.

**Comment by frankhale** [comment]
Apparently two Electron apps running with Crash Reporter started is causing some issues/confusion then. I bet it could be any two Electron apps not just the combination of our app and Atom. I think Atom just linked us to the problem. =)

@OlsonDev, great find! Thank you!

**Comment by hokein** [comment]
Does it happen only on Windows?

**Comment by frankhale** [comment]
I can test on Mac next week (Monday) and report back.

**Comment by marwanhilmi** [comment]
Same behavior for me (v0.30.0)  - it appears to only happen on Windows with multiple Electron apps running. Not able to reproduce behavior on Mac.

**Comment by frankhale** [comment]
Thanks @marwanhilmi for telling us your Mac experiences. This is helpful!

**Comment by ArktekniK** [comment]
I am still experiencing this issue on v33.1, even when I am only running my app
Sometimes I am left with a zombie process after exiting my app which may or may not cause a crash. This has the added side effect that when I relaunch my app, I cannot use the IndexedDB because the previous process still has a lock on the IDB file.

I have to go into task manager and force kill electron.exe

Should I open a new issue on this?

**Comment by ArktekniK** [comment]
Also, I use window cli to launch and kill electron, passing in the path of my JS as an arg.
EG:
electron-v0.33.1-win32-x64\electron.exe Node_Event_Tool\main.js

I don't know if it's my imagination, but it seems the crash happens more frequently when the devtools have been opened.

**Comment by zcbenz** [comment]
@ArktekniK Can you paste the command line parameters of the zombie process? It can be viewed with [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx).

**Comment by ArktekniK** [comment]
Unfortunately, the process only shows
"electron-v0.33.1-win32-x64\electron.exe  Node_Event_Tool\main.js"

I wonder if I'm missing some vital basic shutdown procedure or if the handle on the IDB isn't being properly cleaned up.

**Comment by zcbenz** [comment]
That means the main process doesn't quite, it is probably you didn't call `app.quit`.

**Comment by ArktekniK** [comment]
I am definitely still seeing this problem very often, even when following the sample main.js

````
'use strict';

var app = require('app');
var BrowserWindow = require('browser-window');

let mainWindow = null;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', function() {

  mainWindow = new BrowserWindow({
    'title': 'App title',
    'use-content-size': true,
    'center': true,
    'width': 1220,
    'height': 820,
    'min-width': 1220,
    'min-height': 820,
    'frame': true,
    'node-integration': true,
    'preload': __dirname + '\\preload.js'
  });

  mainWindow.setMenuBarVisibility(false);

  mainWindow.loadUrl('file://' + __dirname + '/public/index.html');

  mainWindow.on('closed', function() {
    mainWindow = null;
  });

  mainWindow.on('page-title-updated', function(event) {
    event.preventDefault();
  });

});
````

It initially looked like the problem would only happen when running the command:
````electron-v0.33.1-win32-x64\electron.exe application\main.js```` and then killing it with a ````Ctrl+C```` My reasoning for this was that the application wasn't receiving the normal termination signal. However, the zombie process is still left around occasionally when closing normally

Any ideas what I am missing in the above code?
