### ISSUE TITLE
Dialogs occasionally not visible in full screen mode on OSX locking application

### ISSUE THREAD

**Issue by isuttell** [atom/electron#2281]
I've been using Atom in fullscreen mode with multiple projects in difference spaces and it works great until occasionally a dialog pops up that isn't visible on the screen but prevents any actions from taking place. For example, I'll hit Save and nothing visually will happen, however the application will stop responding to my input. This has also happened when I tried to exit Atom and it asks if I really want to do that. Opening Mission Control will show the dialog is open but I'm unable to access it. I'm forced to Force Quit the application. I've tried to recreate the problem but I've been unable to come up with a series of steps that cause it. It typically happens after I've been using it for an extended period of time.

I'm using OSX 10.10.3 and Atom 1.0.2.

**Comment by zcbenz** [comment]
This is a bug of OS X, and I believe it has been fixed in 10.10.4.

**Comment by noahbenham** [comment]
I know this issue is closed, but I'm still seeing this behavior with electron 1.4.7 and macOS 10.11.6.
