### ISSUE TITLE
Inspected target disconnected

### ISSUE THREAD

**Issue by paul321** [atom/electron#3832]
I keep getting this issue with latest version of electron 0.36.0. Latest electron build cannot be use with large projects which include requirejs and a lot of bower components. See screenshot, black window it's electron, this happens on both OSX and Windows
![screenshot 2015-12-16 13 37 44](https://cloud.githubusercontent.com/assets/555502/11839991/ecd85a64-a3fa-11e5-95aa-3c4a2d41d467.png)

**Comment by zcbenz** [comment]
We have a few crashes in 0.36.0, they have been fixed on master branch and will be included in next release.

**Comment by paul321** [comment]
Ok thanks hope this one will be fixed too

**Comment by mattdesl** [comment]
I am still getting inspector crashes on `0.36.4`, should I file another bug?

**Comment by alistairheath** [comment]
I am having this issue with 0.36.4 and have narrowed it down to being caused by the serialport module. Unfortunately this a pretty vital part of the application so I can't remove it. Any suggestions? Thanks guys.

**Comment by jaycliff** [comment]
This issue is still persistent in v0.36.7 (IA32), but is seemingly absent in the x64 version.

**Comment by bhanuc** [comment]
Issue persistent on windows 10-32 Bit .

**Comment by BrighTide** [comment]
Can confirm on windows10-64bit v0.36.7 electron-prebuilt. 

Might be an unrelated issue, but narrowed it down to a weird place in my code, basically anytime a property of the global 'location' object is accessed using the 'load' module it crashes the program. 

```
require('load').compiler("console.log(location.hostname)"); //Crashes electron
```

```
require('load').compiler("console.log(document.URL)"); //Works fine
```

```
require('load').compiler("console.log(location)"); //Works fine
```

```
eval("location.hostname"); //Works fine
```

**Comment by spalonytoster** [comment]
Issue persistent on Arch Linux using v0.36.8 electron-prebuilt

**Comment by Teddy-Schmitz** [comment]
Also encountered this on Arch Linux using v0.36.8 electron-prebuilt

**Comment by frenchbread** [comment]
Updated to `electron-prebuilt@0.37.2`. Still facing this issue in addition to black-screen..

**Comment by venomlust** [comment]
electron-prebuilt@0.37.2 same issue, after a few seconds instancing (my case Howler.js) and saving into another variable electron freeze and show black screen

**Comment by frenchbread** [comment]
Well, it seems that there is no black screen issue for me anymore. It took me to rewrite the whole application to figure out the issue.

First of all the app architecture is quite important if this is a multi-window app (like in my case).
But most importantly, after I've updated `electron-prebuilt` to version a `0.37.2` I forgot to change `--version` option in my build script. [Referring](https://github.com/electron-userland/electron-packager#opts) to docs, this option is not required, but still.

So now, build scripts look like this:
```json
"scripts": {
    "start": "electron app.js",
    "build-darwin": "electron-packager . appname --platform=darwin --arch=x64 --version=0.37.2 --ignore=node_modules/electron-*",
    "build-win32": "electron-packager . appname --platform=win32 --arch=x64 --version=0.37.2 --ignore=node_modules/electron-*"
}
```

App builds work well on both MacOSX & Windows 10.

**Comment by spalonytoster** [comment]
electron-prebuilt@0.37.2 now works like a charm. I'm on Arch Linux x64.

**Comment by KT071** [comment]
Still have that problem on electron 1.0.0 ;/

**Comment by jaycliff** [comment]
It seems like this issue is electron-specific (or perhaps chromium-specific), since the latest version of Chrome (51.0.2704.84) doesn't exhibit this behaviour. I am using howler.js (v2 beta) to load up some audio files in my project which somehow triggers the issue, but doesn't happen at all in Chrome.
